export enum SwapType {
    USD     = "USD",
    SYN     = "SYN",
    ETH     = "ETH",
    HIGH    = "HIGHSTREET",
    DOG     = "DOG",
    JUMP    = "JUMP",
    FRAX    = "FRAX",
    NFD     = "NFD",
    OHM     = "OHM",
    GMX     = "GMX",
    SOLAR   = "SOLAR",
    AVAX    = "AVAX",
    MOVR    = "MOVR",
    UST     = "UST",
}