name: Test

on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      matrix:
        node-version:
          - 16
          - 17
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Run Tests
        run: yarn -s run test